name: Various-ShortestPath-Algorithms

on: [push]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    env:
      BUILD_TYPE: Release
      EXE_NAME: ShortestPath
      INPUT_FILES:
      OUTPUT_FILES:
      COMPILER: ${{matrix.config.compiler}}
      COMP: ${{matrix.config.comp}}
      CXXFLAGS: "-Werror"
    timeout-minutes: 3
    strategy:
      matrix:
        config:
          - {
              name: "Ubuntu 20.04 GCC",
              os: ubuntu-20.04,
              compiler: g++,
              comp: gcc,
              shell: 'bash {0}'
          }
    defaults:
      run:
        shell: ${{matrix.config.shell}}

    steps:
      - name: Checkout project repo from GitHub
        uses: actions/checkout@v1

      - name: Executable name Environment Variable Check
        run: |
          echo ${{env.EXE_NAME}}
          echo " "
          echo ${{runner.workspace}}
          echo " "
          echo $GITHUB_WORKSPACE
          echo " "
          $COMPILER --version
          cmake --version

      - name: Create build environment
        run:  mkdir ${{runner.workspace}}/build
        
      - name: Copy InputFiles environment
        run:  cp -r ${{runner.workspace}}/Various-ShortestPath-Algorithms/InputFiles/  ${{runner.workspace}}/build/InputFiles

      - name: Configure the build
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build the project
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE

      - name: Test build
        working-directory: ${{runner.workspace}}/build
        run: make -j2 optimize=no debug=yes > /dev/null
        
      - name: Run the project
        working-directory: ${{runner.workspace}}/build
        run: ./$EXE_NAME $INPUT_FILES $OUTPUT_FILES

      - name: Upload output files to GitHub so they can be reviewed
        uses: actions/upload-artifact@v1
        with:
          name: project_output
          path: ${{runner.workspace}}/build/OutputFiles
